#!/usr/bin/env python3
"""update_ledger.py — regenerate INGESTION-LEDGER.md from the manifest + fetch receipts.

Reads  sources/manifest.json          (what each candidate resolves to)
       scripts/.cache/bulk/_receipts.jsonl  (what has actually been pulled)
Writes INGESTION-LEDGER.md

Run after every fetch:  python3 scripts/update_ledger.py
The amendment log at the bottom of the existing file is preserved and appended to.
"""
import json,os,re,collections,datetime

HERE=os.path.dirname(os.path.abspath(__file__)); ATLAS=os.path.dirname(HERE)
# (manifest, receipts, region label) — the ledger spans both regions
REGIONS=[
 ('Niagara',  os.path.join(ATLAS,'sources','manifest.json'),
              os.path.join(HERE,'.cache','bulk','_receipts.jsonl')),
 ('Hamilton', os.path.join(ATLAS,'sources','manifest-hamilton.json'),
              os.path.join(HERE,'.cache','hamilton','_receipts.jsonl')),
]
LED=os.path.join(ATLAS,'INGESTION-LEDGER.md')
TODAY=datetime.date.today().isoformat()

SECN={'A':'Land, planning and zoning','B':'Infrastructure and servicing','C':'Transportation and logistics',
'D':'Environmental and natural-heritage constraint','E':'Heritage and archaeological constraint',
'F':'Economy, business and employment','G':'Historical imagery and basemaps',
'H':'Labour-force and demographic context','I':'Administrative and reference'}

BLOCK={
 24:('SHP download only, no REST service','A conversion step exists'),
 29:('Catalogue entry links to a portal page, not a service','A service URL appears in the Hub feed'),
 54:('Live feed published as a web page only','—'),
 69:('SHP download only, no REST service','A conversion step exists'),
 80:('404 at every sublayer; not in the Hub cache','`arcgisweb.welland.ca` recovers'),
 91:('ArcGIS error 499 **Token Required** — private layer','Never; needs a credential from Welland'),
 92:('Hub links out; Welland origin server down','`arcgisweb.welland.ca` recovers'),
 104:('Published as a report/CSV landing page','—'),
 105:('StatCan landing page, not a feed','—'),
 106:('Brock server sits behind a **Cloudflare bot challenge** (HTTP 403)','Fetch in a browser, or request access from Brock Map Library'),
 107:('Vector layer returns the mosaic **extent footprint only** (1 polygon), not imagery','Imagery is tile-served; see the raster note'),
 108:('Image service; 1965 mosaic needs another probe path','Retry with an ImageServer probe'),
 109:('Vector layer returns **0 features** — imagery is tile-served, not downloadable','—'),
 111:('Mixed: two series behind the **Cloudflare challenge**, others return 0 features','Fetch in a browser, or request access from Brock Map Library'),
 110:('Index is a document, not a service','—'),
 112:('Gallery page, not a service','—'),
 113:('Image services on `portal.niagarafalls.ca` refused the request','Retry; may be UA or firewall'),
 123:('By-law index is a document listing','—'),
}

def human(b):
    if not b: return '—'
    return f"{b/1e6:.1f} MB" if b>=1e6 else f"{b/1e3:.0f} KB"

def main():
    items=[]; rec=collections.defaultdict(list)
    for region,man,recf in REGIONS:
        if not os.path.exists(man): continue
        for it in json.load(open(man)):
            it['region']=region; items.append(it)
        if os.path.exists(recf):
            for line in open(recf):
                try: r=json.loads(line)
                except Exception: continue
                rec[(r['n'],r['title'])].append(r)
    latest={k:v[-1] for k,v in rec.items()}

    L=[l for it in items for l in it['layers']]
    ok=[l for l in L if l['status']=='ok']
    got=[r for r in latest.values() if r['status'] in ('ok','skip')]
    meta=[r for r in latest.values() if r['status']=='metadata-only']
    failed=[r for r in latest.values() if r['status']=='fail']
    feats=sum(r.get('features') or 0 for r in got if isinstance(r.get('features'),int))
    byts=sum(r.get('bytes') or 0 for r in got)
    blocked=[it for it in items if not any(l['status']=='ok' for l in it['layers'])]

    o=[];w=o.append
    w("# Ingestion ledger — merged Niagara atlas collection\n")
    w("**The authoritative record of what is in the merged collection, where each")
    w("layer came from, and when it was last pulled.** Regenerated by")
    w("`scripts/update_ledger.py` after every fetch. One row per source layer.\n")
    w("Companion to [sources/sources.json](sources/sources.json) (machine registry —")
    w("only gains an entry once a layer is ingested and rendered),")
    w("[sources/manifest.json](sources/manifest.json) (machine twin of this file),")
    w("[CANDIDATES.md](CANDIDATES.md) (the numbered menu),")
    w("[RECON-2026-08-22.md](RECON-2026-08-22.md) and [BACKLOG.md](BACKLOG.md).\n")
    w("`#` is the candidate number from CANDIDATES.md and is **stable** — quote it")
    w("when adding, removing or re-pulling a layer.\n")
    w("---\n## Status\n")
    w("| | |\n|---|---|")
    w("| Selection | Niagara **125 of 126** (all but #98) · Hamilton **89 of 90** (all but #290) |")
    w(f"| Ledger regenerated | **{TODAY}** |")
    w(f"| Source layers resolved | **{len(L)}** |")
    w(f"| Verified reachable | **{len(ok)}** |")
    w(f"| Blocked / no machine endpoint | **{len(L)-len(ok)}** across {len(blocked)} candidates |")
    w(f"| **Downloaded** | **{len(got)}** layers · **{feats:,}** features · **{human(byts)}** |")
    w(f"| Raster services (metadata only) | **{len(meta)}** |")
    w(f"| Fetch failures | **{len(failed)}** |")
    w("")
    w("Local cache lives in `scripts/.cache/bulk/` (Niagara) and `scripts/.cache/hamilton/`")
    w("— **gitignored**, so it does not")
    w("survive a fresh clone. Re-pull with `python3 scripts/fetch_candidates.py`.\n")
    w("> Downloaded ≠ ingested. Nothing here is in `data/` or rendered by the atlas")
    w("> yet; these are local working copies held for engine design.\n")
    w("---\n## Ledger\n")
    w("`Verified` = endpoint answered with a schema. `Pulled` = we hold the file.\n")
    HAMSEC={'A':'Land, planning and zoning','B':'Buildings, permits and vacancy',
      'C':'Infrastructure and servicing','D':'Transportation and logistics',
      'E':'Environmental constraint','F':'Economy, business and employment',
      'G':'Heritage and risk','H':'Reference'}
    for region in ('Niagara','Hamilton'):
        rits=[it for it in items if it.get('region')==region]
        if not rits: continue
        sec=SECN if region=='Niagara' else HAMSEC
        w(f"## {region}\n")
        for k,kn in sec.items():
            grp=[it for it in rits if it['sec']==k]
            if not grp: continue
            w(f"### {region[0]}·{k} — {kn}\n")
            w("| # | Layer | Publisher | Geom | Records | Access | Verified | Pulled | Size |")
            w("|---|---|---|---|---:|---|---|---|---:|")
            for it in grp:
                for i,l in enumerate(it['layers']):
                    num=str(it['n']) if i==0 else '↳'
                    r=latest.get((it['n'],l['title']))
                    if r and isinstance(r.get('features'),int): rc=f"{r['features']:,}"
                    elif isinstance(l.get('count'),int): rc=f"{l['count']:,}"
                    elif l.get('geometry')=='raster': rc='raster'
                    else: rc='—'
                    st='✅' if l['status']=='ok' else '⛔'
                    if r and r['status'] in ('ok','skip'): pulled=f"**{r.get('fetched_at',TODAY)}**"
                    elif r and r['status']=='metadata-only': pulled='meta only'
                    elif r and r['status']=='fail': pulled='⚠ failed'
                    else: pulled='—'
                    org=l['org'].replace('City Of ','').replace('City of ','').replace('Town of ','')
                    w(f"| {num} | {l['title'][:50]} | {org[:15]} | {(l.get('geometry') or '')[:9]} | {rc} | "
                      f"{l.get('access','—')} | {st} | {pulled} | {human(r.get('bytes') if r else None)} |")
            w("")
    w("---\n## Raster and imagery — a different kind of source\n")
    w("The historical imagery in \u00a7G is **not a downloadable dataset**. Each is an")
    w("ArcGIS map or image service that renders tiles on demand; there is no single")
    w("file that constitutes \"the layer\". Where a vector sublayer exists it holds only")
    w("the mosaic's **extent footprint** \u2014 #107 returned one polygon, #109 and the")
    w("1950s/1970s topographic series returned zero features. Service metadata")
    w("(extent, spatial reference, tile scheme, pixel size) is captured as")
    w("`*.service.json`; the imagery itself is consumed as a tile layer at display")
    w("time, or exported at a chosen resolution as a rendering rather than as data.\n")
    w("**Brock University's server (`terra.library.brocku.ca`) is behind a Cloudflare")
    w("bot challenge** and returns HTTP 403 to automated requests \u2014 intermittently,")
    w("which is why some Brock layers resolved and others did not. This is a")
    w("deliberate access control and is not worked around. The 1934/1954/1965/1972")
    w("air photo mosaics remain the most valuable historical evidence found; getting")
    w("them means loading in a browser or asking the **Brock Map Library** directly,")
    w("which as a public academic map library is the reasonable route.\n")
    w("---\n## Blocked — no machine-readable endpoint\n")
    w("Kept in the ledger rather than dropped, so the gap stays visible.\n")
    w("| # | Layer | Publisher | Why | Retry when |")
    w("|---|---|---|---|---|")
    for it in blocked:
        why,retry=BLOCK.get(it['n'],('No machine-readable distribution in catalogue','—'))
        w(f"| {it['n']} | {it['name'][:44]} | {it['pub']} | {why} | {retry} |")
    w("")
    if failed:
        w("---\n## Fetch failures (endpoint verified, download failed)\n")
        w("| # | Layer | Error |\n|---|---|---|")
        for r in sorted(failed,key=lambda x:x['n']):
            w(f"| {r['n']} | {r['title'][:44]} | `{str(r.get('error'))[:80]}` |")
        w("")
    # preserve amendment log
    prev=''
    if os.path.exists(LED):
        m=re.search(r'## Amendment log\n(.*?)(?=\n---\n## Rules|\Z)',open(LED).read(),re.S)
        if m: prev=m.group(1).strip()
    w("---\n## Amendment log\n")
    w("Newest first. Every fetch, re-pull, addition or removal gets a line.\n")
    w(f"- **{TODAY}** — Bulk fetch of all reachable layers. {len(got)} layers held")
    w(f"  locally ({feats:,} features, {human(byts)}) in `scripts/.cache/bulk/`.")
    w(f"  {len(meta)} raster services captured as metadata only. {len(failed)} fetch failures.")
    if prev:
        for ln in prev.split('\n'):
            if ln.strip().startswith('- **') and TODAY not in ln: w(ln)
            elif ln.startswith('  ') and w(ln) is None: pass
    w("")
    w("---\n## Rules for amending this file\n")
    w("1. **Regenerate, don't hand-edit** — run `scripts/update_ledger.py`. The")
    w("   amendment log is the one part carried across regenerations.")
    w("2. **One row per source layer**, never per candidate — a candidate bundling")
    w("   three by-laws gets three rows, so a partial pull stays visible.")
    w("3. **`Verified` and `Pulled` are different facts** and must not be conflated.")
    w("4. **Record counts are observed**, never estimated.")
    w("5. **Blocked layers stay listed.** Removing one hides the gap.")
    w("6. **A layer only enters `sources/sources.json` when it is actually rendered**")
    w("   in the atlas, with its own probe and licence line. This ledger runs ahead")
    w("   of that registry by design.")
    open(LED,'w').write('\n'.join(o)+'\n')
    print(f"ledger: {len(L)} layers | {len(got)} pulled | {feats:,} features | {human(byts)}")

if __name__=='__main__': main()
